#!/bin/bash

if [ -z "$COMPOSER_FLAGS" ]; then
    COMPOSER_FLAGS=
fi

echo "Backing up package state ..."
composerBackup=$(cat composer.json)

composer remove --dev -n nyholm/psr7 php-http/guzzle6-adapter

testImplementation() {
    echo "Testing $1 version $2 ..."
    echo
    composer require --dev -n $COMPOSER_FLAGS "$1" "$2"
    composer test-client || return 1
    composer remove --dev -n "$1"
    echo
    return 0
}

testImplementation php-http/guzzle6-adapter "^2.0" || exit 1

echo "Resetting package state ..."
echo "$composerBackup" > composer.json
composer update -n -q $COMPOSER_FLAGS
