#!/bin/bash

if [ -z "$COMPOSER_FLAGS" ]; then
    COMPOSER_FLAGS=
fi

echo "Backing up package state ..."
composerBackup=$(cat composer.json)

composer remove --dev -n nyholm/psr7 php-http/guzzle6-adapter

echo "Composer clear cache ..."
composer clearcache

testImplementation() {
    echo "Testing $1 version $2 ..."
    echo

    if [[ $TRAVIS_PHP_VERSION && ${TRAVIS_PHP_VERSION:0:3} < "7.2" && $1 == "sunrise/http-factory" ]]
    then
        echo "$1 skipped due to unsupported php version."
        echo
        return 0
    fi

    composer require --dev -n $COMPOSER_FLAGS "$1" "$2"
    composer test-factory || return 1
    composer remove --dev -n "$1"
    echo
    return 0
}

testImplementation nyholm/psr7 "^1.0" || exit 1
testImplementation http-interop/http-factory-diactoros "^1.0" || exit 1
testImplementation http-interop/http-factory-guzzle "^1.0" || exit 1
testImplementation http-interop/http-factory-slim "^1.0" || exit 1
testImplementation zendframework/zend-diactoros "^2.0" || exit 1
testImplementation sunrise/http-factory "^1.0" || exit 1

echo "Resetting package state ..."
echo "$composerBackup" > composer.json
composer update -n -q $COMPOSER_FLAGS
